[package]
name = "day1_2"
version = "0.1.0"
edition = "2021"
target = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"
